### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by yanbowe** [KiWi233333/jiwu-mall-chat-tauri#1]
作者您好，我运行项目一直启动不起来
![image](https://github.com/user-attachments/assets/86edd4a4-3f4f-471d-9e9b-d20e08442123)

**Comment by KiWi233333** [comment]
@yanbowe 
1. 开一个终端先运行 pnpm dev:nuxt
2. 再开一个终端运行 pnpm dev:tauri
可不分后顺序

这样子做是因为nuxt启动较慢，比如只修改了tauri不用nuxt也被动重启

**Comment by KiWi233333** [comment]
警告告诉你在3000端口没有 前端服务

**Comment by yanbowe** [comment]
> @yanbowe
> 
> 1. 开一个终端先运行 pnpm dev:nuxt
> 2. 再开一个终端运行 pnpm dev:tauri
>    可不分后顺序
> 
> 这样子做是因为nuxt启动较慢，比如只修改了tauri不用nuxt也被动重启

谢谢已经运行成功，账号密码需要自己注册吗？

**Comment by yanbowe** [comment]
项目的eslint规则好像需要优化
![image](https://github.com/user-attachments/assets/20680331-161c-40e7-89eb-3ddbec154ff5)

**Comment by KiWi233333** [comment]
> > @yanbowe
> > 
> > 1. 开一个终端先运行 pnpm dev:nuxt
> > 2. 再开一个终端运行 pnpm dev:tauri
> >    可不分后顺序
> > 
> > 这样子做是因为nuxt启动较慢，比如只修改了tauri不用nuxt也被动重启
> 
> 谢谢已经运行成功，账号密码需要自己注册吗？

需要的，或者用默认ikun233 123456
